# SEO settings
title: "Hey guy, Welcome to "
title2: "Turing Ant!" # default: ""
description: "Just another minimalist Jekyll theme that focuses on technical writing."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://turingant.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
cdsn: http://blog.csdn.net/turingant #CSDN
weibo: http://weibo.com/u/5866291988 #Sina Weibo
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://turingant.github.io
disqus_shortname: "Turing Ant"
twitter_username: "Turing Ant"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Turing Ant"
  job      : "R&D Software Engineer"
  bio      : "1+1=3 is always TRUE in my world, a balance between binary and reality."
  thumb    : /images/author.jpg
  email    : hnrird@gmail.com
  url      : http://turingant.github.io
  github   : http://github.com/turingant
  twitter  : #
  facebook : #
  linkedin : #

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "Turing Ant"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
